[web_servers]
13.38.73.162 ansible_user=ubuntu ansible_ssh_private_key_file=/c/Users/holal/Documents/IPSSI/projets_aws/aws-cli-v2/infra/terraform/claire-davs-key.pem

[web_servers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
